import type { Opportunity } from "@/types/opportunity"

/**
 * Mock opportunity dataset for Sprint 1 (Core Feed UI).
 *
 * Timestamps are generated relative to module load so the feed always shows a
 * realistic mix of "fresh", "active" and "closing soon" states. In production
 * this is replaced by the Firestore-backed discovery agent output.
 */

const NOW = Date.now()
const HOUR = 60 * 60 * 1000
const DAY = 24 * HOUR

const hoursAgo = (h: number) => new Date(NOW - h * HOUR).toISOString()
const daysFromNow = (d: number) => new Date(NOW + d * DAY).toISOString()

export const OPPORTUNITIES: Opportunity[] = [
  {
    id: "op-001",
    slug: "eskom-electrical-apprenticeship-gauteng",
    title: "Electrical Apprenticeship",
    organisation: "Eskom Holdings",
    city: "Johannesburg",
    province: "gauteng",
    trade: "electrical",
    type: "apprenticeship",
    salary: { kind: "stipend", min: 4500 },
    foundAt: hoursAgo(2),
    closesAt: daysFromNow(2),
    summary:
      "Three-year electrical apprenticeship with structured trade-test preparation at one of South Africa's largest utilities.",
    aiSummary:
      "A funded apprenticeship that pays a monthly stipend while you work toward your electrical trade test. Strong fit for N2/N3 holders wanting a recognised qualification.",
    requirements: [
      "Grade 12 with Maths and Physical Science",
      "N2 Electrical (advantageous)",
      "South African ID",
      "Valid driver's licence (advantageous)",
    ],
    applyUrl: "https://www.eskom.co.za/careers",
    source: "EWSETA",
    verified: true,
  },
  {
    id: "op-002",
    slug: "merseta-welding-learnership-ekurhuleni",
    title: "Welding Learnership (NQF Level 3)",
    organisation: "MERSETA Accredited Centre",
    city: "Ekurhuleni",
    province: "gauteng",
    trade: "welding",
    type: "learnership",
    salary: { kind: "stipend", min: 3500 },
    foundAt: hoursAgo(5),
    closesAt: daysFromNow(9),
    summary:
      "Twelve-month welding learnership covering arc, MIG and TIG welding with a recognised NQF Level 3 qualification on completion.",
    requirements: [
      "Grade 10 minimum",
      "Aged 18–35",
      "Physically fit",
      "South African ID",
    ],
    applyUrl: "https://www.merseta.org.za/learnerships",
    source: "MERSETA",
    verified: true,
  },
  {
    id: "op-003",
    slug: "transnet-plumbing-apprenticeship-durban",
    title: "Plumbing Apprenticeship",
    organisation: "Transnet SOC",
    city: "Durban",
    province: "kwazulu-natal",
    trade: "plumbing",
    type: "apprenticeship",
    salary: { kind: "stipend", min: 5200 },
    foundAt: hoursAgo(8),
    closesAt: daysFromNow(20),
    summary:
      "Apprenticeship in industrial plumbing and pipefitting across Transnet's port and rail infrastructure.",
    requirements: [
      "Grade 12 with Maths",
      "N2 in a relevant trade",
      "No criminal record",
    ],
    applyUrl: "https://www.transnet.net/careers",
    source: "TETA",
    verified: true,
  },
  {
    id: "op-004",
    slug: "sasol-mechanical-fitter-learnership-secunda",
    title: "Mechanical Fitter Learnership",
    organisation: "Sasol",
    city: "Secunda",
    province: "mpumalanga",
    trade: "mechanical",
    type: "learnership",
    salary: { kind: "stipend", min: 6800 },
    foundAt: hoursAgo(14),
    closesAt: daysFromNow(12),
    summary:
      "Fitting and turning learnership at Sasol's Secunda operations with a clear path to trade-test certification.",
    requirements: [
      "Grade 12 with Maths and Physical Science (50%+)",
      "N3 Mechanical (advantageous)",
      "South African citizen",
    ],
    applyUrl: "https://www.sasol.com/careers",
    source: "CHIETA",
    verified: true,
  },
  {
    id: "op-005",
    slug: "city-of-cape-town-hvac-job-cape-town",
    title: "HVAC Technician",
    organisation: "City of Cape Town",
    city: "Cape Town",
    province: "western-cape",
    trade: "hvac",
    type: "job",
    salary: { kind: "salary", min: 18000, max: 24000 },
    foundAt: hoursAgo(20),
    closesAt: daysFromNow(6),
    summary:
      "Permanent HVAC technician role maintaining municipal building climate systems across the metro.",
    requirements: [
      "Trade-tested HVAC / Refrigeration",
      "3+ years experience",
      "Valid driver's licence",
      "Gas handling certificate",
    ],
    applyUrl: "https://www.capetown.gov.za/careers",
    source: "PNet",
    verified: false,
  },
  {
    id: "op-006",
    slug: "toyota-automotive-apprenticeship-durban",
    title: "Motor Mechanic Apprenticeship",
    organisation: "Toyota South Africa",
    city: "Durban",
    province: "kwazulu-natal",
    trade: "automotive",
    type: "apprenticeship",
    salary: { kind: "stipend", min: 5000 },
    foundAt: hoursAgo(26),
    closesAt: daysFromNow(18),
    summary:
      "Automotive apprenticeship at Toyota's Prospecton plant, training toward a motor mechanic trade test.",
    requirements: [
      "Grade 12 with Maths and Science",
      "N2 Motor Mechanics",
      "Aged 18–25",
    ],
    applyUrl: "https://www.toyota.co.za/careers",
    source: "MERSETA",
    verified: true,
  },
  {
    id: "op-007",
    slug: "wbho-construction-bursary-national",
    title: "Construction Management Bursary 2026",
    organisation: "WBHO Construction",
    city: "Johannesburg",
    province: "gauteng",
    trade: "construction",
    type: "bursary",
    salary: { kind: "funded" },
    foundAt: hoursAgo(30),
    closesAt: daysFromNow(28),
    summary:
      "Full bursary covering tuition, accommodation and a book allowance for construction management studies.",
    requirements: [
      "Accepted into a recognised tertiary programme",
      "Matric average 65%+",
      "Financial need",
    ],
    applyUrl: "https://www.wbho.co.za/bursaries",
    source: "CETA",
    verified: true,
  },
  {
    id: "op-008",
    slug: "anglo-american-mining-learnership-limpopo",
    title: "Underground Mining Learnership",
    organisation: "Anglo American",
    city: "Mokopane",
    province: "limpopo",
    trade: "mining",
    type: "learnership",
    salary: { kind: "stipend", min: 7500 },
    foundAt: hoursAgo(34),
    closesAt: daysFromNow(15),
    summary:
      "Mining learnership covering rock-breaking and underground safety, with a recognised MQA qualification.",
    requirements: [
      "Grade 12",
      "Medically fit for underground work",
      "Reside within 50km of site",
    ],
    applyUrl: "https://www.angloamerican.com/careers",
    source: "MQA",
    verified: true,
  },
  {
    id: "op-009",
    slug: "vodacom-ict-learnership-gauteng",
    title: "ICT Network Support Learnership",
    organisation: "Vodacom",
    city: "Midrand",
    province: "gauteng",
    trade: "ict",
    type: "learnership",
    salary: { kind: "stipend", min: 6000 },
    foundAt: hoursAgo(40),
    closesAt: daysFromNow(11),
    summary:
      "Twelve-month ICT learnership focused on network support and CompTIA certification.",
    requirements: [
      "Grade 12 with Maths",
      "Basic computer literacy",
      "Aged 18–30",
    ],
    applyUrl: "https://www.vodacom.co.za/careers",
    source: "MICT SETA",
    verified: true,
  },
  {
    id: "op-010",
    slug: "kwv-agriculture-learnership-western-cape",
    title: "Agricultural Operations Learnership",
    organisation: "KWV",
    city: "Paarl",
    province: "western-cape",
    trade: "agriculture",
    type: "learnership",
    salary: { kind: "stipend", min: 4000 },
    foundAt: hoursAgo(46),
    closesAt: daysFromNow(22),
    summary:
      "Hands-on agricultural learnership across viticulture and farm operations in the Cape Winelands.",
    requirements: ["Grade 10 minimum", "Willing to work outdoors", "South African ID"],
    applyUrl: "https://www.kwv.co.za/careers",
    source: "AgriSETA",
    verified: false,
  },
  {
    id: "op-011",
    slug: "imperial-logistics-job-gauteng",
    title: "Warehouse Forklift Operator",
    organisation: "Imperial Logistics",
    city: "Kempton Park",
    province: "gauteng",
    trade: "logistics",
    type: "job",
    salary: { kind: "salary", min: 9000, max: 12000 },
    foundAt: hoursAgo(52),
    closesAt: daysFromNow(4),
    summary:
      "Forklift operator role in a high-volume distribution centre with shift allowances.",
    requirements: [
      "Valid forklift licence",
      "1+ year warehouse experience",
      "Able to work shifts",
    ],
    applyUrl: "https://www.imperiallogistics.com/careers",
    source: "Careers24",
    verified: false,
  },
  {
    id: "op-012",
    slug: "edcon-clothing-machinist-learnership-kzn",
    title: "Clothing Machinist Learnership",
    organisation: "Prestige Clothing",
    city: "Cape Town",
    province: "western-cape",
    trade: "clothing",
    type: "learnership",
    salary: { kind: "stipend", min: 3500 },
    foundAt: hoursAgo(60),
    closesAt: daysFromNow(16),
    summary:
      "Industrial sewing machinist learnership with placement into a cut-make-trim factory.",
    requirements: ["Grade 9 minimum", "Good hand-eye coordination", "Aged 18–35"],
    applyUrl: "https://example.com/prestige-careers",
    source: "FP&M SETA",
    verified: false,
  },
  {
    id: "op-013",
    slug: "eskom-electrician-trade-test-mpumalanga",
    title: "Electrician Trade Test",
    organisation: "Eskom Holdings",
    city: "Witbank",
    province: "mpumalanga",
    trade: "electrical",
    type: "trade-test",
    salary: { kind: "funded" },
    foundAt: hoursAgo(66),
    closesAt: daysFromNow(8),
    summary:
      "Subsidised electrical trade test for candidates who have completed their workplace hours.",
    requirements: [
      "Completed apprenticeship logbook",
      "N3 Electrical",
      "Section 13 / 28 eligible",
    ],
    applyUrl: "https://www.eskom.co.za/careers",
    source: "EWSETA",
    verified: true,
  },
  {
    id: "op-014",
    slug: "bosch-short-course-diesel-gauteng",
    title: "Diesel Systems Short Course",
    organisation: "Bosch Training Centre",
    city: "Pretoria",
    province: "gauteng",
    trade: "automotive",
    type: "short-course",
    salary: { kind: "funded" },
    foundAt: hoursAgo(72),
    closesAt: daysFromNow(25),
    summary:
      "Two-week intensive short course on modern common-rail diesel injection systems.",
    requirements: ["Basic automotive knowledge", "Grade 12 advantageous"],
    applyUrl: "https://example.com/bosch-training",
    source: "MERSETA",
    verified: true,
  },
  {
    id: "op-015",
    slug: "rand-water-plumbing-learnership-gauteng",
    title: "Plumbing Learnership",
    organisation: "Rand Water",
    city: "Vereeniging",
    province: "gauteng",
    trade: "plumbing",
    type: "learnership",
    salary: { kind: "stipend", min: 4800 },
    foundAt: hoursAgo(78),
    closesAt: daysFromNow(13),
    summary:
      "Water-sector plumbing learnership focused on bulk water reticulation and maintenance.",
    requirements: ["Grade 12 with Maths", "N2 Plumbing advantageous", "South African ID"],
    applyUrl: "https://www.randwater.co.za/careers",
    source: "EWSETA",
    verified: true,
  },
  {
    id: "op-016",
    slug: "afrox-welding-job-eastern-cape",
    title: "Coded Welder",
    organisation: "Afrox",
    city: "Port Elizabeth",
    province: "eastern-cape",
    trade: "welding",
    type: "job",
    salary: { kind: "salary", min: 15000, max: 22000 },
    foundAt: hoursAgo(90),
    closesAt: daysFromNow(5),
    summary:
      "Coded welding role on pressure-vessel fabrication with overtime opportunities.",
    requirements: ["Coded welding certificate", "3+ years fabrication", "Own transport"],
    applyUrl: "https://www.afrox.co.za/careers",
    source: "PNet",
    verified: false,
  },
  {
    id: "op-017",
    slug: "samancor-mining-bursary-north-west",
    title: "Mining Engineering Bursary",
    organisation: "Samancor Chrome",
    city: "Rustenburg",
    province: "north-west",
    trade: "mining",
    type: "bursary",
    salary: { kind: "funded" },
    foundAt: hoursAgo(96),
    closesAt: daysFromNow(30),
    summary:
      "Bursary for mining engineering studies with vacation work and a guaranteed interview.",
    requirements: ["Accepted for Mining Engineering", "Matric 70%+ in Maths and Science"],
    applyUrl: "https://example.com/samancor-bursary",
    source: "MQA",
    verified: true,
  },
  {
    id: "op-018",
    slug: "telkom-ict-job-free-state",
    title: "Field Network Technician",
    organisation: "Telkom",
    city: "Bloemfontein",
    province: "free-state",
    trade: "ict",
    type: "job",
    salary: { kind: "salary", min: 14000, max: 19000 },
    foundAt: hoursAgo(40),
    closesAt: daysFromNow(10),
    summary:
      "Field technician role installing and maintaining fibre and copper network infrastructure.",
    requirements: ["N6 / Diploma in Electronics", "Valid driver's licence", "2+ years field experience"],
    applyUrl: "https://www.telkom.co.za/careers",
    source: "MICT SETA",
    verified: true,
  },
  {
    id: "op-019",
    slug: "group-five-construction-job-northern-cape",
    title: "Site Carpenter",
    organisation: "Stefanutti Stocks",
    city: "Kimberley",
    province: "northern-cape",
    trade: "construction",
    type: "job",
    salary: { kind: "salary", min: 11000, max: 16000 },
    foundAt: hoursAgo(120),
    closesAt: null,
    summary:
      "Site carpenter for formwork and shuttering on a major civil infrastructure project.",
    requirements: ["Trade-tested carpenter", "Formwork experience", "Willing to relocate"],
    applyUrl: "https://example.com/stefanutti-careers",
    source: "CETA",
    verified: false,
  },
  {
    id: "op-020",
    slug: "denel-mechanical-apprenticeship-gauteng",
    title: "Toolmaker Apprenticeship",
    organisation: "Denel",
    city: "Centurion",
    province: "gauteng",
    trade: "mechanical",
    type: "apprenticeship",
    salary: { kind: "stipend", min: 5500 },
    foundAt: hoursAgo(3),
    closesAt: daysFromNow(17),
    summary:
      "Precision toolmaking apprenticeship with exposure to CNC and conventional machining.",
    requirements: ["Grade 12 with Maths and Science", "N2 Engineering", "South African citizen"],
    applyUrl: "https://example.com/denel-careers",
    source: "MERSETA",
    verified: true,
  },
  {
    id: "op-021",
    slug: "santam-hvac-learnership-western-cape",
    title: "Refrigeration Learnership",
    organisation: "SA Refrigeration Academy",
    city: "Cape Town",
    province: "western-cape",
    trade: "hvac",
    type: "learnership",
    salary: { kind: "stipend", min: 4200 },
    foundAt: hoursAgo(6),
    closesAt: daysFromNow(3),
    summary:
      "Refrigeration and air-conditioning learnership with SAQCC gas registration support.",
    requirements: ["Grade 11 minimum", "Aged 18–30", "Physically fit"],
    applyUrl: "https://example.com/refrigeration-academy",
    source: "EWSETA",
    verified: false,
  },
  {
    id: "op-022",
    slug: "barloworld-logistics-learnership-kzn",
    title: "Supply Chain Learnership",
    organisation: "Barloworld",
    city: "Pinetown",
    province: "kwazulu-natal",
    trade: "logistics",
    type: "learnership",
    salary: { kind: "stipend", min: 5000 },
    foundAt: hoursAgo(10),
    closesAt: daysFromNow(14),
    summary:
      "Supply chain and warehousing learnership with rotation across distribution functions.",
    requirements: ["Grade 12", "Computer literate", "Aged 18–35"],
    applyUrl: "https://example.com/barloworld-careers",
    source: "TETA",
    verified: true,
  },
  {
    id: "op-023",
    slug: "tongaat-agriculture-job-kzn",
    title: "Irrigation Technician",
    organisation: "Tongaat Hulett",
    city: "Tongaat",
    province: "kwazulu-natal",
    trade: "agriculture",
    type: "job",
    salary: { kind: "salary", min: 10000, max: 14000 },
    foundAt: hoursAgo(16),
    closesAt: daysFromNow(7),
    summary:
      "Irrigation technician maintaining centre-pivot and drip systems across sugarcane estates.",
    requirements: ["Irrigation experience", "Valid driver's licence", "Mechanical aptitude"],
    applyUrl: "https://example.com/tongaat-careers",
    source: "AgriSETA",
    verified: false,
  },
  {
    id: "op-024",
    slug: "expired-electrical-job-gauteng",
    title: "Maintenance Electrician",
    organisation: "Premier Foods",
    city: "Isando",
    province: "gauteng",
    trade: "electrical",
    type: "job",
    salary: { kind: "salary", min: 16000, max: 20000 },
    foundAt: hoursAgo(180),
    closesAt: daysFromNow(-2),
    summary:
      "Maintenance electrician for a food-processing plant. Wireman's licence preferred.",
    requirements: ["Trade-tested electrician", "Wireman's licence", "FMCG experience advantageous"],
    applyUrl: "https://example.com/premier-careers",
    source: "FoodBev SETA",
    verified: false,
  },
]

export function getAllOpportunities(): Opportunity[] {
  return OPPORTUNITIES
}

export function getOpportunityBySlug(slug: string): Opportunity | undefined {
  return OPPORTUNITIES.find((o) => o.slug === slug)
}

export function getRelatedOpportunities(
  opportunity: Opportunity,
  limit = 3,
): Opportunity[] {
  return OPPORTUNITIES.filter(
    (o) =>
      o.id !== opportunity.id &&
      (o.trade === opportunity.trade || o.province === opportunity.province),
  ).slice(0, limit)
}
