#!/usr/bin/env bash
export PATH="/home/lx_singw/.npm-global/bin:/home/lx_singw/google-cloud-sdk/bin:$PATH"
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="${ROOT}/apps/web/.env.local"

echo "=== Step 5: Environment Variables (.env.local) ==="

# Don't overwrite if it already has real values
if [ -f "${ENV_FILE}" ] && grep -q "AIza" "${ENV_FILE}" 2>/dev/null; then
  echo ".env.local already configured with Firebase keys. Skipping."
  exit 0
fi

mkdir -p "$(dirname "${ENV_FILE}")"

cat > "${ENV_FILE}" << 'EOF'
# ─────────────────────────────────────────────────────────────────
# Skilved — Development Environment Variables
# Generated by: scripts/setup/firebase-env-setup.sh
#
# FILL IN the values marked with <your-...>
# Get them from: https://console.firebase.google.com/project/skilved-dev/settings/general
#
# NEVER commit this file to git (it's in .gitignore)
# ─────────────────────────────────────────────────────────────────

# ── App ───────────────────────────────────────────────────────────
NEXT_PUBLIC_APP_ENV=development
NEXT_PUBLIC_APP_URL=http://localhost:3000

# ── Firebase (Public — safe to expose in browser) ─────────────────
# Get from: Firebase Console → Project Settings → Your apps → Web app config
NEXT_PUBLIC_FIREBASE_API_KEY=<your-firebase-api-key>
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=skilved-dev.firebaseapp.com
NEXT_PUBLIC_FIREBASE_PROJECT_ID=skilved-dev
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=skilved-dev.appspot.com
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=<your-sender-id>
NEXT_PUBLIC_FIREBASE_APP_ID=<your-app-id>

# ── Firebase Admin (Server-side ONLY — never expose to browser) ───
# Get from: Firebase Console → Project Settings → Service Accounts → Generate new private key
FIREBASE_PROJECT_ID=skilved-dev
FIREBASE_CLIENT_EMAIL=<your-service-account-email>
FIREBASE_PRIVATE_KEY="<your-private-key-with-newlines>"

# ── Auth ──────────────────────────────────────────────────────────
NEXTAUTH_SECRET=<run: openssl rand -base64 32>
NEXTAUTH_URL=http://localhost:3000

# ── Gemini AI ─────────────────────────────────────────────────────
# Get from: https://aistudio.google.com/app/apikey  (free!)
GEMINI_API_KEY=<your-gemini-api-key>

# ── Firebase Emulators (local dev — don't change) ─────────────────
FIRESTORE_EMULATOR_HOST=localhost:8080
FIREBASE_AUTH_EMULATOR_HOST=localhost:9099
FIREBASE_STORAGE_EMULATOR_HOST=localhost:9199

# ── Feature Flags (Sprint 1 defaults) ────────────────────────────
FEATURE_SKILLS_PULSE_DASHBOARD=true
FEATURE_CAREER_AGENT=true
FEATURE_AI_COVER_NOTE=true
FEATURE_MATCHING_EXPLANATIONS=true
FEATURE_IN_APP_APPLY=false
FEATURE_MYMZANSI_VERIFY=false
FEATURE_EMPLOYER_DASHBOARD=false
FEATURE_COLLECTIVE_INTELLIGENCE=false
FEATURE_CAREER_SIMULATION=false
FEATURE_MICRO_CREDENTIALS=false
FEATURE_CAPTCHA_SOLVER=false
FEATURE_APPLICATION_AGENT=false

# ── BigQuery (stubbed — skip in Spark/free mode) ──────────────────
# These won't work until billing is enabled — leave as-is for now
BIGQUERY_DATASET=skilved_dev
BIGQUERY_ENABLED=false

# ── Redis (stubbed — use in-memory cache in dev) ──────────────────
REDIS_ENABLED=false

# ── Phase 2 (leave blank for now) ────────────────────────────────
PAYFAST_MERCHANT_ID=
PAYFAST_MERCHANT_KEY=
WHATSAPP_API_TOKEN=
CAPTCHA_SOLVER_API_KEY=
EOF

echo "Written: apps/web/.env.local"
echo ""
echo "ACTION REQUIRED — fill in these values:"
echo "  1. Firebase config  → https://console.firebase.google.com/project/skilved-dev/settings/general"
echo "  2. Service account  → Firebase Console → Project Settings → Service Accounts"
echo "  3. NEXTAUTH_SECRET  → run: openssl rand -base64 32"
echo "  4. GEMINI_API_KEY   → https://aistudio.google.com/app/apikey (free)"
